FROM centos:7
MAINTAINER Zenoss <dev@zenoss.com>

ENV TERM xterm

COPY scrub.sh /sbin/scrub.sh

# Update packages
RUN yum --setopt=tsflags="nodocs" update -y

# Install some useful tools
# Update yum_package_list.txt to change the set of installed RPM packages.
RUN yum install -y --setopt=tsflags="nodocs" %PACKAGES%

# Install the httpie rpm instead of pip installing it
RUN yum install epel-release -y \
    && yum install httpie -y \
    && yum erase epel-release -y

RUN wget -q http://zenpip.zenoss.eng/packages/ActivePython-2.7.18.0000-linux-x86_64-glibc-2.17-67a601ea.tar.gz -O /root/ActivePython.tar.gz
RUN tar -C /root --transform="s,ActivePython-2.7.18.0000-linux-x86_64-glibc-2.17-67a601ea,ActivePython," -x -f ActivePython.tar.gz
RUN /root/ActivePython/install.sh -I /opt/activepython

# Install pip
RUN wget -qO- https://bootstrap.pypa.io/get-pip.py | python; \
    pip install --no-cache-dir supervisor

# Install setuser script
RUN wget -q https://raw.githubusercontent.com/phusion/baseimage-docker/master/image/bin/setuser -O /sbin/setuser \
    && sed -ie 's/python3/python/' /sbin/setuser \
    && chmod a+x /sbin/setuser 

# Install jq to work with JSON
RUN wget -q https://github.com/stedolan/jq/releases/download/jq-1.5/jq-linux64 -O /usr/bin/jq \
	&& chmod a+x /usr/bin/jq

# Add symlink for vim
RUN ln -s /usr/bin/vi /usr/bin/vim

# Add TERM=xterm to /root/.bashrc
RUN echo "export TERM=xterm" >> /root/.bashrc

ENV JAVA_HOME /usr/lib/jvm/jre

RUN /sbin/scrub.sh
